<?php
/**
 * Created by PhpStorm.
 * User: 11070
 * Date: 2021/10/24
 * Time: 0:30
 */
namespace PhpEasyData\Tests;
use PhpEasyData\Components\ConfigEnv;
use PhpEasyData\Tests\Model\UserModel;
use PHPUnit\Framework\TestCase;

$file_load_path = '../../../autoload.php';
if (file_exists($file_load_path)) {
    include $file_load_path;
} else {
    include '../vendor/autoload.php';
}
class SearchTest extends TestCase{
    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        ConfigEnv::loadFile('.env');
    }

    public function testTime(){
       var_dump(ConfigEnv::get('elasticSearch.host'));
    }


    public function testInsert(){
      $user = new UserModel();
      $res = $user->insert(['name' => 111]);
      print_r($res);
    }

}